github:
  user: "updatebot"
  email: "updatebot@olblak.com"
  username: "jenkins-infra-bot"
  token: "UPDATECLI_GITHUB_TOKEN" 
  branch: "master"
  owner: "jenkins-infra"
  repository: "docker-mirrorbits"
